quarkus:
  mongodb:
    database: palindrome
    connection-string: mongodb://mongodb-palindrome:27017

  datasource:
    mongodb:
      uri: mongodb://mongodb-palindrome:27017
      collections:
        - palindrome

  log:
    category:
      "io.quarkus.category":
        level: INFO

  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8082

feature-flag:
  matrix-length:
    min: 5
    max: 10
  palindrome-length:
    min: 4
