quarkus:

  datasource:
    db-kind: postgresql
    username: root
    password: R3c1f3
    reactive:
      url: postgresql://10.10.0.253:5432/palindrome

  log:
    category:
      "io.quarkus.category":
        level: INFO

  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8082

feature-flag:
  matrix-length:
    min: 5
    max: 10
  palindrome-length:
    min: 4
