quarkus:

  devservices:
    enabled: false

  datasource:
    db-kind: postgresql
    username: root
    password: R3c1f321!
    reactive:
      url: postgresql://maranguape.a3sitsolutions.com.br:5432/palindrome
  log:
    category:
      "io.quarkus.category":
        level: INFO

  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8080

  oidc:
    auth-server-url: https://keycloak.maranguape.a3sitsolutions.com.br/auth/realms/palindrome

  smallrye-openapi:
    security-scheme: oidc
    oidc-open-id-connect-url: https://keycloak.maranguape.a3sitsolutions.com.br/auth/realms/palindrome/.well-known/openid-configuration

feature-flag:
  matrix-length:
    min: 5
    max: 10
  palindrome-length:
    min: 4